groups:
- name: example
  rules:
  - alert: HighErrorRate
    expr: job:request_errors:rate5m{job="app-backend"} > 0.05
    for: 5m
    labels:
      severity: critical
    annotations:
      summary: High request error rate on app-backend
      description: "Error rate is {{ $value }} over the last 5 minutes."
