{
 "title": "Prediction App Metrics",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  { "title": "Application specific", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Scam percentage over time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    { "expr": "scam_percentage", "legendFormat": "{{__name__}}" }
   ]
  },
  {
   "title": "Scam Percentage (Now)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "scam_percentage", "legendFormat": "{{label_name}}" }
   ]
  },
  {
   "title": "Total Prediction Request",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    { "expr": "page_requests_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Rate of Prediction requests [1 min]",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(prediction_requests_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Prediction latency by quantile (  0.9, 0.95, 0.99)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, prediction_latency_seconds_bucket)",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.95, prediction_latency_seconds_bucket)",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.99, prediction_latency_seconds_bucket)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Prediction latency Histogram",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "prediction_latency_seconds_count",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Application Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "CPU  Process [current interval]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": " Page Requests rate [current interval]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "rate(page_requests_created[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Allocated memory ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "targets": [
    { "expr": "go_memstats_alloc_bytes", "legendFormat": "__auto" }
   ]
  }
 ]
}