services:
  model-service:
    image: ghcr.io/remla24-team8/model-service:v0.1.0
    container_name: model-service
    volumes:
        - model-service-model-volume:/model-service/models

    healthcheck:
      test: ".venv/bin/python model_service/health.py"
      interval: 2s
      timeout: 30s
      retries: 15

  app-backend:
    image: ghcr.io/remla24-team8/app-backend:v0.2.1
    container_name: app-backend
    depends_on:
     model-service:
       condition: service_healthy
    ports:
      - "127.0.0.1:5000:5000"
    environment:
      MODEL_SERVICE_URL: 'http://model-service:5000'
      
  app-frontend:
    image: ghcr.io/remla24-team8/app-frontend:v0.1.1
    container_name: app-frontend
    depends_on:
     model-service:
       condition: service_healthy
    ports:
      - "127.0.0.1:3000:80"
    environment:
      BACKEND_URL: 'http://localhost:5000'

volumes:
  model-service-model-volume:
    driver: local
    name: model-service-model-volume

networks:
  default:
    name: remla24-team8
