---
- hosts: controller
  roles:
    - role: geerlingguy.docker
      vars:
        docker_users:
          - vagrant
  become: yes
  tasks:
    - name: Update and upgrade apt packages
      apt:
        update_cache: yes
        upgrade: dist

    

    