# This file is partially based on https://github.com/k3s-io/k3s-ansible by Vincent Rabah, Derek Nola
---
- name: Install k3s
  hosts: k3s_cluster
  become: yes
  tasks:
    - name: Get k3s installed version
      ansible.builtin.command: k3s --version
      register: k3s_version_output
      changed_when: false
      ignore_errors: true
    - name: Set k3s installed version
      when: k3s_version_output.rc == 0
      ansible.builtin.set_fact:
        installed_k3s_version: "{{ k3s_version_output.stdout_lines[0].split(' ')[2] }}"
    - name: Download artifact only if needed
      when: k3s_version_output.rc != 0 or installed_k3s_version is version(k3s_version, '<')
      block:
        - name: Download K3s install script
          ansible.builtin.get_url:
            url: https://get.k3s.io/
            timeout: 120
            dest: /usr/local/bin/k3s-install.sh
            owner: root
            group: root
            mode: 0755

        - name: Download K3s binary
          ansible.builtin.command:
            cmd: /usr/local/bin/k3s-install.sh
          environment:
            INSTALL_K3S_SKIP_START: "true"
            INSTALL_K3S_VERSION: "{{ k3s_version }}"
          changed_when: true

- name: Start k3s server
  hosts: server
  become: yes
  tasks:
    - name: Run install/start
      ansible.builtin.command:
        cmd: /usr/local/bin/k3s-install.sh
      environment:
        K3S_TOKEN: mytoken
        INSTALL_K3S_SKIP_DOWNLOAD: "true"
        INSTALL_K3S_EXEC: "--node-ip {{ node_ip }} --flannel-iface eth1 --disable servicelb,traefik,local-storage" 

- name: Start k3s agent
  hosts: agent
  become: yes
  tasks:
    - name: Run install/start
      ansible.builtin.command:
        cmd: /usr/local/bin/k3s-install.sh
      environment:
        K3S_TOKEN: mytoken
        INSTALL_K3S_SKIP_DOWNLOAD: "true"
        K3S_URL: https://10.10.10.100:6443
        INSTALL_K3S_EXEC: "--node-ip {{ node_ip }} --flannel-iface eth1" 

    