---
- hosts: all
  become: yes
  tasks:
    - name: Update and upgrade apt packages
      apt:
        update_cache: yes
        upgrade: dist

    - name: Install basic packages
      apt:
        name:
          - git
          - curl
          - apt-transport-https
          - ca-certificates
          - software-properties-common
        state: present

    - name: Install Docker
      apt:
        name: docker.io
        state: present