n_workers = 2

# the '2' means the Vagrant config version for Vagrant 1.1+
Vagrant.configure ("2") do |config|
  # # base box: https://app.vagrantup.com/bento/boxes/ubuntu-24.04
  # config.vm.box = "bento/ubuntu-24.04"
  # # specific version for 'bento/ubuntu-24.04'
  # config.vm.box_version = "202404.26.0"
  # config.vm.network "private_network", type: "dhcp"
  # # set the hostname
  # config.vm.hostname = "controller"

  # config.vm.provider "virtualbox" do |v|
  #   v.memory = 4096
  #   v.cpus = 2
  # end

  # config.vm.provision "shell", path: "update_inventory.sh"

  config.vm.define "controller" do |control|
    control.vm.box = "bento/ubuntu-24.04"
    config.vm.box_version = "202404.26.0"
    control.vm.hostname = "controller"
    config.vm.network "private_network", type: "dhcp"
    control.vm.provider "virtualbox" do |vb|
      vb.memory = 4096
      vb.cpus = 2
    end

    config.vm.provision :ansible do |ansible|  
      compatibility_mode = "2.0"
      ansible.playbook = "playbook.yml"
    end
  end

  # Configure the worker nodes
  (1..n_workers).each do |i|
    config.vm.define "node#{i}" do |worker|
      worker.vm.box = "bento/ubuntu-24.04"
      config.vm.box_version = "202404.26.0"
      worker.vm.hostname = "node#{i}"
      config.vm.network "private_network", type: "dhcp"

      worker.vm.provider "virtualbox" do |vb|
        vb.memory = 4096
        vb.cpus = 2
      end

    end
  end

  config.ssh.insert_key = false

  # config.vm.provision :ansible do |ansible|  
  #   compatibility_mode = "2.0"
  #   ansible.playbook = "playbook.yml"  
  # end
end