NODE_ROLES = ["server-0", "agent-0", "agent-1"]

NODE_CPUS = 2
NODE_MEMORY = 4096
# Virtualbox >= 6.1.28 require `/etc/vbox/network.conf` for expanded private networks 
NETWORK_PREFIX = "10.10.10"

def provision(vm, role, node_num)
  vm.box = "bento/ubuntu-24.04"
  # specific version for 'bento/ubuntu-24.04
  vm.box_version = "202404.26.0"
  vm.hostname = role
  # We use a private network because the default IPs are dynamically assigned 
  # during provisioning. This makes it impossible to know the server-0 IP when 
  # provisioning subsequent servers and agents. A private network allows us to
  # assign static IPs to each node, and thus provide a known IP for the API endpoint.
  node_ip = "#{NETWORK_PREFIX}.#{node_num+100}"
  # An expanded netmask is required to allow VM<-->VM communication, virtualbox defaults to /32
  vm.network "private_network", ip: node_ip, netmask: "255.255.255.0"

  vm.provider "virtualbox" do |v|
    v.memory = NODE_MEMORY
    v.cpus = NODE_CPUS
  end

  vm.provision "ansible", run: 'once' do |ansible|
    ansible.compatibility_mode = "2.0"
    ansible.playbook = "playbooks/general.yml"
    ansible.groups = {
      "server" => NODE_ROLES.grep(/^server/),
      "agent" => NODE_ROLES.grep(/^agent/),
      "k3s_cluster:children" => ["server", "agent"],
    }
    ansible.extra_vars = {
      k3s_version: "v1.30.0+k3s1",
      node_ip: node_ip
    }
  end
end

# the '2' means the Vagrant config version for Vagrant 1.1+
Vagrant.configure ("2") do |config|
  NODE_ROLES.each_with_index do |name, i|
    config.vm.define name do |node|
      provision(node.vm, name, i)
    end
  end

  config.ssh.insert_key = false
end