apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: flask-app-monitor
  labels:
    release: prom
spec:
  selector:
    matchLabels:
      app: flask-app
  endpoints:
  - interval: 30s
    port: http
