apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: my-gateway
spec:
  selector:
    istio: ingress
  servers:
  - port: { number: 80, name: http , protocol: HTTP }
    hosts: [ "*" ]
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: my-entry-service
spec:
  gateways: [ my-gateway ]
  hosts: [ "*" ]
  http:
    - match:
      - uri:
          prefix: /
      route:
        - destination:
            host: app-frontend-service
            subset: v2
          weight: 90
        - destination:
            host: app-frontend-service
            subset: canary
          weight: 10
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: app-dr
spec:
  host: app-frontend-service
  subsets:
    - name: v2
      labels: { version: v2 }
    - name: canary
      labels: { version: canary }
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: app-backend-dr
spec:
  host: app-backend-service
  subsets:
    - name: v2
      labels: { version: v2 }
    - name: canary
      labels: { version: canary }
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: app-backend-vs
spec:
  gateways: [ my-gateway ]
  hosts: [ "*" ]
  http:
    - match:
      - uri:
          prefix: /api
      rewrite:
        uri: /
      route:
        - destination:
            host: app-backend-service
            subset: v2
          weight: 50
        - destination:
            host: app-backend-service
            subset: canary
          weight: 50