{
 "title": "Prediction App Metrics-G8",
 "panels": [
  { "title": "Application specific", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Scam percentage over time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "scam_percentage" }
   ]
  },
  {
   "title": "Scam Percentage (Now)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    { "expr": "scam_percentage" }
   ]
  },
  {
   "title": "Total Prediction Request",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "page_requests_total" }
   ]
  },
  {
   "title": "Increase of Prediction requests [1 min]",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(prediction_requests_total[1m])"
    }
   ]
  },
  {
   "title": "Prediction latency by quantile (0.9, 0.95, 0.99)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, rate(prediction_latency_seconds_bucket[5m]))"
    },
    {
     "expr": "histogram_quantile(0.95, rate(prediction_latency_seconds_bucket[5m]))"
    },
    {
     "expr": "histogram_quantile(0.99, rate(prediction_latency_seconds_bucket[5m]))"
    }
   ]
  },
  {
   "title": "Prediction Latency Histogram",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "prediction_latency_seconds_count"
    }
   ]
  },
  { "title": "Application Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "CPU  Process [current interval]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total[$__rate_interval])"
    }
   ]
  },
  {
   "title": "Page Requests rate [current interval]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "rate(page_requests_total[$__rate_interval])"
    }
   ]
  },
  {
   "title": "Allocated memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "targets": [
    { "expr": "go_memstats_alloc_bytes" }
   ]
  }
 ]
}