---
- hosts: controller
  become: yes
  tasks:
    - name: Install Helm
      shell: curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

    - name: Install Kubernetes Dashboard via Helm
      shell: |
        helm repo add kubernetes-dashboard https://kubernetes.github.io/dashboard/
        helm install kubernetes-dashboard kubernetes-dashboard/kubernetes-dashboard --namespace kubernetes-dashboard --create-namespace

    - name: Create admin service account for Kubernetes Dashboard
      shell: |
        kubectl create serviceaccount admin-user -n kubernetes-dashboard
        kubectl create clusterrolebinding admin-user-binding --clusterrole=cluster-admin --serviceaccount=kubernetes-dashboard:admin-user

    - name: Install Prometheus via Helm
      shell: |
        helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
        helm repo update
        helm install prometheus prometheus-community/prometheus --namespace monitoring --create-namespace

    - name: Install Grafana via Helm
      shell: |
        helm repo add grafana https://grafana.github.io/helm-charts
        helm repo update
        helm install grafana grafana/grafana --namespace monitoring --create-namespace
